CREATE TABLE orders (
    order_id INT,
    customer_id VARCHAR(10),
    order_date DATE,
    amount DECIMAL(10, 2),
    product_category VARCHAR(50)
);
INSERT INTO orders (order_id, customer_id, order_date, amount, product_category)
VALUES  (1, 'C1', '2024-01-01', 100.00, 'Electronics'),
(2, 'C1', '2024-01-05', 200.00, 'Clothing'),
(3, 'C2', '2024-01-07', 150.00, 'Electronics'),
(4, 'C3', '2024-01-10', 300.00, 'Clothing'),
(5, 'C3', '2024-02-15', 250.00, 'Furniture'),
(6, 'C4', '2024-01-20', 400.00, 'Electronics'),
(7, 'C4', '2024-02-22', 350.00, 'Furniture'),
(8, 'C5', '2024-01-25', 500.00, 'Clothing'),
(9, 'C5', '2024-01-30', 600.00, 'Furniture'),
(10,'C5', '2024-02-10', 800.00, 'Clothing'),
(11, 'C1', '2023-01-01', 100.00, 'Electronics'),
(12, 'C1', '2023-01-05', 200.00, 'Clothing'),
(13, 'C2', '2023-01-07', 150.00, 'Electronics'),
(14, 'C3', '2023-01-10', 300.00, 'Clothing'),
(15, 'C3', '2023-02-15', 250.00, 'Furniture'),
(16, 'C4', '2023-01-20', 400.00, 'Electronics');

SELECT * FROM ORDERS;

#Total amount spent by each customer

SELECT
CUSTOMER_ID, SUM(AMOUNT) AS TOTALORDER_AMOUNT
FROM ORDERS
GROUP BY CUSTOMER_ID;

#Total amount spent by each customer in each product category

SELECT
CUSTOMER_ID, PRODUCT_CATEGORY, SUM(AMOUNT) AS TOTALORDER_AMOUNT
FROM ORDERS
GROUP BY CUSTOMER_ID,PRODUCT_CATEGORY;

SELECT
PRODUCT_CATEGORY,
COUNT(*) AS TOTALORDERCNT
FROM ORDERS
GROUP BY PRODUCT_CATEGORY;

SELECT
PRODUCT_CATEGORY,
AVG(AMOUNT) AS AVG_ORDERAMT
FROM ORDERS
GROUP BY PRODUCT_CATEGORY;

SELECT
CUSTOMER_ID, MAX(AMOUNT)
FROM ORDERS
GROUP BY CUSTOMER_ID;

SELECT
CUSTOMER_ID, MIN(AMOUNT)
FROM ORDERS
GROUP BY CUSTOMER_ID;

SELECT
CUSTOMER_ID,
COUNT(*) AS TOTAL_ORDERS
FROM ORDERS
GROUP BY CUSTOMER_ID;

SELECT
PRODUCT_CATEGORY,
SUM(AMOUNT) AS TOTAL_SALEAMT
FROM ORDERS
GROUP BY PRODUCT_CATEGORY;

SELECT
CUSTOMER_ID,
AVG(AMOUNT) AS AVG_ORDERAMT
FROM ORDERS
GROUP BY CUSTOMER_ID;

SELECT
COUNT(DISTINCT CUSTOMER_ID) AS NO_OF_CUSTOMERS,
PRODUCT_CATEGORY
FROM ORDERS
GROUP BY PRODUCT_CATEGORY;

SELECT 
MONTH(ORDER_DATE) AS Month,
YEAR(ORDER_DATE) AS YEAR,
SUM(Amount) AS TotalAmountSpent
FROM ORDERS
GROUP BY MONTH(ORDER_DATE),YEAR(ORDER_DATE)
ORDER BY Month;


SELECT 
MONTH(ORDER_DATE) AS Month,
YEAR(ORDER_DATE) AS YEAR,
AVG(Amount) AS AVGAmountSpent
FROM ORDERS
GROUP BY MONTH(ORDER_DATE),YEAR(ORDER_DATE)
ORDER BY Month;

SELECT
MONTH(ORDER_DATE) AS Month,
YEAR(ORDER_DATE) AS YEAR,
COUNT(ORDER_ID) AS ORDERS_PER_MONTH
FROM ORDERS
GROUP BY MONTH(ORDER_DATE),YEAR(ORDER_DATE);


SELECT
YEAR(ORDER_DATE) AS YEAR,
SUM(AMOUNT) AS TOTALAMT
FROM ORDERS
GROUP BY YEAR(ORDER_DATE);

SELECT
YEAR(ORDER_DATE) AS YEAR,
AVG(AMOUNT) AS AVGAMOUNT
FROM ORDERS
GROUP BY YEAR(ORDER_DATE);


SELECT
PRODUCT_CATEGORY,
COUNT(ORDER_ID) AS NO_OF_ORDERS,
YEAR(ORDER_DATE) AS YEAR
FROM ORDERS
GROUP BY PRODUCT_CATEGORY,YEAR(ORDER_DATE);

SELECT
CUSTOMER_ID,
SUM(AMOUNT) AS AMT_SPENTPER_YEAR,
YEAR(ORDER_DATE) AS YEAR
FROM ORDERS
GROUP BY CUSTOMER_ID, YEAR(ORDER_DATE);


SELECT
PRODUCT_CATEGORY,
MAX(AMOUNT) AS MAXORDER_AMT,
YEAR(ORDER_DATE) AS YEAR
FROM ORDERS
GROUP BY PRODUCT_CATEGORY, YEAR(ORDER_DATE);

SELECT
PRODUCT_CATEGORY,
MIN(AMOUNT) AS MINORDER_AMT,
YEAR(ORDER_DATE) AS YEAR
FROM ORDERS
GROUP BY PRODUCT_CATEGORY, YEAR(ORDER_DATE);

SELECT
PRODUCT_CATEGORY,
AVG(AMOUNT) AS AVGORDER_AMT,
YEAR(ORDER_DATE) AS YEAR
FROM ORDERS
GROUP BY PRODUCT_CATEGORY, YEAR(ORDER_DATE);
